#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

#Depending on the operating system of the host machines(s) that will build or run the containers, the image specified in the FROM statement may need to be changed.
#For more information, please see https://aka.ms/containercompat

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["TranslationManagement.Api/TranslationManagement.Api.csproj", "TranslationManagement.Api/"]
COPY ["External.ThirdParty.Services/External.ThirdParty.Services.csproj", "External.ThirdParty.Services/"]
COPY ["TranslationManagement.Application/TranslationManagement.Application.csproj", "TranslationManagement.Application/"]
COPY ["TranslationManagement.Data/TranslationManagement.Data.csproj", "TranslationManagement.Data/"]
COPY ["TranslationManagement.Domain/TranslationManagement.Domain.csproj", "TranslationManagement.Domain/"]
RUN dotnet restore "TranslationManagement.Api/TranslationManagement.Api.csproj"
COPY . .
WORKDIR "/src/TranslationManagement.Api"
RUN dotnet build "TranslationManagement.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "TranslationManagement.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TranslationManagement.Api.dll"]